export enum RepositoryEnum {
  CAREER_REPOSITORY = 'CAREER_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  CURRICULUM_REPOSITORY = 'CURRICULUM_REPOSITORY',
  INFORMATION_STUDENT_REPOSITORY = 'INFORMATION_STUDENT_REPOSITORY',
  INFORMATION_TEACHER_REPOSITORY = 'INFORMATION_TEACHER_REPOSITORY',
  INSTITUTION_REPOSITORY = 'INSTITUTION_REPOSITORY',
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  STUDENT_REPOSITORY = 'STUDENT_REPOSITORY',
  SUBJECT_REPOSITORY = 'SUBJECT_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',


  //
  //Cronograma
  CRONOGRAMA_REPOSITORY = 'CRONOGRAMA_REPOSITORY',
  TAREA_REPOSITORY = 'TAREA_REPOSITORY',


  //Dignidad
  CANDIDATO_REPOSITORY = 'CANDIDATO_REPOSITORY',
  CARGO_REPOSITORY = 'CARGO_REPOSITORY',
  LISTAS_REPOSITORY = 'LISTAS_REPOSITORY',
  TIPO_LISTA_REPOSITORY = 'TIPO_LISTA_REPOSITORY',



  //CARRERA
  CARRERA_REPOSITORY = 'CARRERA_REPOSITORY',

  //SUFRAGIO
  VOTO_REPOSRITORY = 'VOTO_REPOSRITORY',
}
